FROM ubuntu
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -qq update && \
    apt-get -yqq install krb5-user libpam-krb5 curl iputils-ping && \
    apt-get -yqq clean

WORKDIR /work/

RUN chmod "g+rwX" /work
COPY --chmod=774 target/*-runner /work/application
COPY --chmod=774 podman/docker_entrypoint_start-quarkus.sh /work/docker_entrypoint_start-quarkus.sh

RUN mkdir -p /work/keytabs

EXPOSE 8080
EXPOSE 88/tcp
EXPOSE 88/udp

ENTRYPOINT ["/work/docker_entrypoint_start-quarkus.sh"]
